- name: Create Nginx directory
  file:
    path: /opt/nginx
    state: directory
    mode: 644

- name: Remove old Nginx configuration file if present
  file:
    path: /opt/nginx/nginx.conf
    state: absent

- name: Upload new Nginx configuration file
  template:
    src: ../template/nginx.tmpl
    dest: /opt/nginx/nginx.conf


- name: Set up Nginx in Docker Container
  docker_container:
    name: nginx
    image: nginx:latest
    state: started
    restart_policy: unless-stopped
    ports:
      - "80:80"
    volumes:
        - /opt/nginx/nginx.conf:/etc/nginx/nginx.conf